### ISSUE TITLE
mongodb报错

### ISSUE THREAD

**Issue by BeautyQAQ** [FX-Max/docker-install-everything#62]
执行`docker-compose up -d mongodb`后报错如下
mapping values are not allowed in this context

将yml文件中13行的`TZ='Asia/Shanghai'`改为`TZ: 'Asia/Shanghai'`后成功执行

系统版本：CentOS 8
docker版本：20.10.17
Docker Compose version v2.9.0

**Comment by FX-Max** [comment]
感谢，已修复。
应该是旧版本遗留的。
